name: Test
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/typst/typst:latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile nordic.typ
        run: typst compile nordic.typ

      - name: Create local package folder
        run: mkdir -p ~/.local/share/typst/packages/local/nordic/0.1.0
      - name: Copy files into package folder
        run: cp -r . ~/.local/share/typst/packages/local/nordic/0.1.0

      # Create file which imports locally installed package
      - name: Create testfile
        run: echo '#import "@local/nordic:0.1.0"' >> testfile.typ
      - name: Compile testfile
        run: typst compile testfile.typ

      - name: Compile Test Files
        run: for file in $(ls tests); do typst compile tests/$file --root . ; done
